 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Adie", "adie", "/usr/share/pixmaps/adie.png" },
     {"Archive Manager", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"Atom", "electron --app=/usr/lib/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Battery Charge Graph", "/usr/bin/battery-graph", "///usr/share/battery-stats/pixmaps/battery-stats.png" },
     {"Battery Level Graph", "/usr/share/battery-stats/battery-stats-graph", "///usr/share/battery-stats/pixmaps/battery-stats.png" },
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"ClipIt", "clipit"},
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"FOX Calculator", "calculator", "/usr/share/pixmaps/calculator.png" },
     {"Files", "nautilus --new-window ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Nautilus.png" },
     {"Fonts", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Go For It!", "go-for-it", "/usr/share/icons/hicolor/16x16/apps/go-for-it.svg" },
     {"GooglePlayDownloader", "googleplaydownloader", "/usr/share/pixmaps/googleplaydownloader.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.6/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"KeePassXC", "keepassxc ", "/usr/share/icons/hicolor/16x16/apps/keepassxc.png" },
     {"Marp", "/usr/bin/marp", "/usr/share/pixmaps/marp.png" },
     {"PCManFM File Manager", "pcmanfm-qt ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"PlayOnLinux", "playonlinux"},
     {"Qemu Launcher", "qemu-launcher"},
     {"Shutter", "shutter ", "/usr/share/icons/hicolor/16x16/apps/shutter.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Waterfall", "waterfall"},
     {"Winetricks", "winetricks --gui"},
     {"WizNote", "WizNote", "/usr/share/icons/hicolor/16x16/apps/wiznote.png" },
     {"Xchm", "xchm ", "/usr/share/pixmaps/xchm-48.png" },
     {"Xournal", "xournal "},
     {"Zim Desktop Wiki", "zim ", "/usr/share/pixmaps/zim.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"chinese-calendar", "/usr/bin/chinese-calendar", "/usr/share/pixmaps/chinesecalendar-64.png" },
     {"compton", "compton --xrender-sync-fence", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"fcitx-qimpanel-configtool", "fcitx-qimpanel-configtool", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
     {"krop", "krop ", "/usr/share/icons/gnome/16x16/actions/edit-cut.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"DrRacket", "drracket -singleInstance ", "/usr/share/icons/hicolor/16x16/apps/drracket.png" },
     {"FreeCAD", "/usr/bin/freecad ", "/usr/share/icons/hicolor/16x16/apps/freecad.png" },
     {"GNU Octave", "/usr/bin/octave --force-gui ", "/usr/share/icons/hicolor/16x16/apps/octave.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GNU TeXmacs", "texmacs ", "/usr/share/pixmaps/TeXmacs.xpm" },
     {"GeoGebra", "geogebra"},
     {"GoldenDict", "goldendict", "/usr/share/pixmaps/goldendict.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Maple 2016", "/opt/maple2016/bin/xmaple", "///opt/maple2016/bin/Maple2016.png" },
     {"Mathomatic", "xterm -e mathomatic", "/usr/share/pixmaps/mathomatic.png" },
     {"Matlab", "matlab -desktop -nosplash", "/usr/share/pixmaps/matlab.png" },
     {"Mendeley Desktop", "mendeleydesktop ", "/usr/share/icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"QReduce", "xterm -e qreduce", "///usr/share/qreduce/Bumblebee.png" },
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
     {"Redcsl", "xterm -e redcsl", "/usr/share/icons/redcsl.png" },
     {"SageMath", "xterm -e /usr/bin/sage -notebook=sagenb", "/usr/share/pixmaps/sage-notebook.png" },
     {"Singular", "xterm -e Singular", "///usr/share/icons/Singular.png" },
     {"Stellarium", "stellarium", "/usr/share/icons/hicolor/16x16/apps/stellarium.png" },
     {"Xcas", "xcas ", "/usr/share/icons/hicolor/16x16/apps/xcas.png" },
     {"lenmus", "lenmus", "/usr/share/pixmaps/lenmus.png" },
     {"wxMaxima", "wxmaxima ", "/usr/share/pixmaps/wxmaxima.png" },
     {"xmaxima", "xmaxima", "/usr/share/pixmaps/maxima-new.png" },
     {"yacas-gui", "yacas-gui", "/usr/share/icons/hicolor/16x16/apps/yacas-gui.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Fceux", "/usr/bin/fceux", "///usr/share/pixmaps/fceux.png" },
     {"OpenRA - Dune 2000", "openra-d2k", "/usr/share/icons/hicolor/16x16/apps/openra-d2k.png" },
     {"OpenRA - Red Alert", "openra-ra", "/usr/share/icons/hicolor/16x16/apps/openra-ra.png" },
     {"OpenRA - Tiberian Dawn", "openra-cnc", "/usr/share/icons/hicolor/16x16/apps/openra-cnc.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"Xboard", "xboard", "/usr/share/icons/hicolor/48x48/apps/xboard.png" },
     {"bastet", "xterm -e bastet", "/usr/share/pixmaps/bastet.png" },
     {"higan", "higan", "/usr/share/pixmaps/higan.png" },
     {"mGBA", "mgba-qt ", "/usr/share/icons/hicolor/16x16/apps/mgba.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Blender", "blender ", "/usr/share/icons/hicolor/16x16/apps/blender.png" },
     {"Darktable", "/usr/bin/darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"DjView4", "djview4 ", "/usr/share/icons/hicolor/32x32/mimetypes/djvulibre-djview4.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"FreeWRL", "/usr/bin/freewrl", "/usr/share/pixmaps/freewrl.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"GV", "gv", "/usr/share/pixmaps/gv.xbm" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Gpick", "gpick", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/calligrakrita.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MComix", "mcomix ", "/usr/share/icons/hicolor/16x16/apps/mcomix.png" },
     {"Master PDF Editor 4", "/opt/master-pdf-editor-4/masterpdfeditor4 ", "///opt/master-pdf-editor-4/masterpdfeditor4.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"OpenSCAD", "openscad ", "/usr/share/pixmaps/openscad.png" },
     {"PDF Editor", "pdfedit", "///usr/share/pdfedit/icon/pdfedit_logo.png" },
     {"QtQR", "qtqr", "/usr/share/pixmaps/qtqr.png" },
     {"Scribus", "scribus ", "/usr/share/icons/hicolor/32x32/apps/scribus.png" },
     {"Shotwell", "shotwell ", "/usr/share/icons/hicolor/16x16/apps/shotwell.png" },
     {"Slideshow", "/usr/bin/slideshow", "///usr/share/racket/slideshow-exe-icon.png" },
     {"XDot", "xdot "},
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/gthumb.png" },
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"115pan", "115pan", "/usr/share/pixmaps/115pan.png" },
     {"4K Video Downloader", "4kvideodownloader", "/usr/share/pixmaps/4kvideodownloader.png" },
     {"Audio assistant", "linphone --run-audio-assistant", "/usr/share/icons/hicolor/48x48/apps/linphone.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BCloud", "bcloud-gui", "/usr/share/icons/hicolor/16x16/apps/bcloud.png" },
     {"Charles", "charles ", "/usr/share/icons/hicolor/16x16/apps/charles.png" },
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Chromium-dev Web Browser", "/usr/bin/chromium-dev ", "/usr/share/icons/hicolor/16x16/apps/chromium-dev.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"Ekiga Softphone", "ekiga", "/usr/share/icons/hicolor/16x16/apps/ekiga.png" },
     {"Electronic WeChat", "/usr/bin/electronic-wechat", "///usr/share/electronic-wechat/assets/icon.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Firefox Developer Edition", "/usr/lib/firefox-developer-edition/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox-developer-edition.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-unstable.png" },
     {"HexChat", "hexchat --existing ", "/usr/share/icons/hicolor/48x48/apps/hexchat.png" },
     {"Linphone", "linphone ", "/usr/share/icons/hicolor/48x48/apps/linphone.png" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Min", "min", "/usr/share/icons/hicolor/256x256/apps/min.png" },
     {"Navicat Lite", "/usr/bin/navicat", "///opt/navicat/Navicat/help/img/icon_navicat.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Point", "/opt/Point/PointDownload/PointDownload", "///opt/Point/PointDownload/point.png" },
     {"Rocket.Chat+", "\"/opt/Rocket.Chat+/rocketchat\" "},
     {"ScudCloud", "scudcloud", "///usr/share/pixmaps/scudcloud.png" },
     {"Slack", "env LD_PRELOAD=/usr/lib/libcurl.so.3 /usr/bin/slack --disable-gpu ", "/usr/share/pixmaps/slack.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TIM", "\"/opt/deepinwine/apps/Deepin-TIM/run.sh\" ", "/usr/share/icons/hicolor/16x16/apps/deepin.com.qq.office.svg" },
     {"Thunderbird", "/usr/lib/thunderbird/thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Tickr - Feed Reader", "/usr/bin/tickr", "///usr/share/tickr/pixmaps/tickr-icon.xpm" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser", "///usr/share/pixmaps/tor-browser.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"Xware Desktop", "/usr/bin/xware-desktop ", "/usr/share/icons/hicolor/16x16/apps/xware-desktop.png" },
     {"Yandex Browser (beta)", "/usr/bin/yandex-browser-beta ", "/usr/share/icons/hicolor/16x16/apps/yandex-browser-beta.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"lftp", "xterm -e lftp", "/usr/share/icons/hicolor/48x48/apps/lftp-icon.png" },
     {"qutebrowser", "qutebrowser ", "/usr/share/icons/hicolor/16x16/apps/qutebrowser.png" },
     {"weweChat", "/usr/bin/weweChat", "///usr/share/weweChat/resource/128x128.png" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"E-book Editor", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"EclipseTrader", "/usr/share/eclipsetrader/trader", "///usr/share/pixmaps/eclipsetrader.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"GV", "gv", "/usr/share/pixmaps/gv.xbm" },
     {"GnuCash", "gnucash ", "/usr/share/icons/hicolor/16x16/apps/gnucash-icon.png" },
     {"GoldenDict", "goldendict", "/usr/share/pixmaps/goldendict.png" },
     {"Gummi", "gummi ", "/usr/share/pixmaps/gummi.png" },
     {"HTMLDOC", "htmldoc ", "/usr/share/icons/hicolor/16x16/apps/htmldoc.png" },
     {"KchmViewer", "kchmviewer ", "/usr/share/pixmaps/kchmviewer.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"LyX", "lyx ", "/usr/share/icons/hicolor/48x48/apps/lyx.png" },
     {"Master PDF Editor 4", "/opt/master-pdf-editor-4/masterpdfeditor4 ", "///opt/master-pdf-editor-4/masterpdfeditor4.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"PDFsam", "pdfsam", "/usr/share/pixmaps/pdfsam.png" },
     {"ReText", "/usr/bin/retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"TeXstudio", "texstudio ", "/usr/share/icons/hicolor/16x16/apps/texstudio.png" },
     {"TeXworks", "texworks ", "/usr/share/pixmaps/TeXworks.png" },
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
     {"WPS Presentation", "/usr/bin/wpp ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wppmain.png" },
     {"WPS Spreadsheets", "/usr/bin/et ", "/usr/share/icons/hicolor/48x48/apps/wps-office-etmain.png" },
     {"WPS Writer", "/usr/bin/wps ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wpsmain.png" },
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.svg" },
     {"Zathura", "zathura "},
     {"Zotero", "/usr/bin/zotero ", "/usr/share/icons/hicolor/16x16/apps/zotero.png" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Logical Volume Management", "/usr/bin/system-config-lvm", "///usr/share/system-config-lvm/pixmaps/lv_icon.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"Atom", "electron --app=/usr/lib/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"BlueGriffon", "bluegriffon", "/usr/share/icons/hicolor/16x16/apps/bluegriffon.png" },
     {"Bluefish Editor", "bluefish ", "/usr/share/icons/hicolor/16x16/apps/bluefish.png" },
     {"Burp Suite Free Edition", "burpsuite", "/usr/share/pixmaps/burpsuite.png" },
     {"CLion", "\"/opt/clion/bin/clion.sh\" ", "///opt/clion/bin/clion.svg" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Charles", "charles ", "/usr/share/icons/hicolor/16x16/apps/charles.png" },
     {"CoqIDE Proof Assistant", "coqide", "/usr/share/pixmaps/coqide.png" },
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"DrRacket", "drracket -singleInstance ", "/usr/share/icons/hicolor/16x16/apps/drracket.png" },
     {"DreamPie", "dreampie", "/usr/share/pixmaps/dreampie.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Genymotion", "/usr/bin/genymotion", "///opt/genymotion/icons/icon.png" },
     {"Genymotion Player", "/usr/bin/genymotion-player"},
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Gluon Scene Builder", "gluon-scenebuilder", "/usr/share/pixmaps/gluon-scenebuilder.png" },
     {"Hopper Disassembler v4", "/opt/hopper-v4/bin/Hopper ", "/usr/share/icons/hicolor/16x16/apps/hopper-disassembler-v4.png" },
     {"IDA Demo", "/opt/ida-demo/idaq", "/usr/share/icons/hicolor/64x64/apps/ida.png" },
     {"IntelliJ IDEA Ultimate Edition", "intellij-idea-ultimate-edition ", "/usr/share/pixmaps/intellij-idea-ultimate-edition.png" },
     {"Julia", "xterm -e julia"},
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.6/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"LiteIDE", "liteide", "/usr/share/pixmaps/liteide.png" },
     {"Marp", "/usr/bin/marp", "/usr/share/pixmaps/marp.png" },
     {"Matlab", "matlab -desktop -nosplash", "/usr/share/pixmaps/matlab.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"NVIDIA Visual Profiler", "/opt/cuda/bin/nvvp", "///opt/cuda/libnvvp/icon.xpm" },
     {"Nsight Eclipse Edition", "/opt/cuda/bin/nsight", "///opt/cuda/libnsight/icon.xpm" },
     {"OmegaT", "omegat", "/usr/share/pixmaps/omegat.svg" },
     {"OpenJDK 1.7.0 Monitoring & Management Console", "/usr/lib/jvm/java-7-openjdk/bin/jconsole"},
     {"OpenJDK 1.7.0 Policy Tool", "/usr/lib/jvm/java-7-openjdk/jre/bin/policytool"},
     {"Poedit", "poedit ", "/usr/share/icons/hicolor/16x16/apps/poedit.png" },
     {"PyCharm", "\"/opt/pycharm-professional/bin/pycharm.sh\" ", "///opt/pycharm-professional/bin/pycharm.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "qtcreator ", "/usr/share/icons/hicolor/16x16/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"RStudio", "/usr/bin/rstudio-bin ", "/usr/share/icons/hicolor/16x16/apps/rstudio.png" },
     {"Spyder for Python 2.x", "spyder2 ", "/usr/share/pixmaps/spyder2.png" },
     {"Spyder for Python 3.x", "spyder3 ", "/usr/share/pixmaps/spyder3.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
     {"sandbox", "xterm -e sandbox", "/usr/share/pixmaps/sandbox.svg" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"CoqIDE Proof Assistant", "coqide", "/usr/share/pixmaps/coqide.png" },
     {"Julia", "xterm -e julia"},
     {"Mathematica 11", "/usr/bin/Mathematica ", "/usr/share/icons/hicolor/32x32/apps/wolfram-mathematica.png" },
     {"Spyder for Python 2.x", "spyder2 ", "/usr/share/pixmaps/spyder2.png" },
     {"Spyder for Python 3.x", "spyder3 ", "/usr/share/pixmaps/spyder3.png" },
     {"XDot", "xdot "},
     {"Yacas", "xterm -e yacas", "/usr/share/icons/hicolor/16x16/apps/yacas-gui.png" },
     {"Yacas online documentation", "xdg-open https://yacas.readthedocs.org/", "/usr/share/icons/hicolor/16x16/apps/yacas-gui.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Aegisub", "aegisub-3.2 ", "/usr/share/icons/hicolor/16x16/apps/aegisub.png" },
     {"Ardour 5", "ardour5", "///usr/share/ardour5/resources/Ardour-icon_256px.png" },
     {"Ario", "ario", "/usr/share/icons/hicolor/16x16/apps/ario.png" },
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Baidu Yun Player", "mpv --http-header-fields='User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0','Connection: keep-alive','Referer:http://pan.baidu.com/disk/home'  ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"Baka-MPlayer", "baka-mplayer ", "/usr/share/pixmaps/baka-mplayer.svg" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"DeaDBeeF", "deadbeef ", "/usr/share/icons/hicolor/16x16/apps/deadbeef.png" },
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GTK sound mixer", "/usr/bin/aumix", "///usr/share/aumix/aumix.xpm" },
     {"Gespeaker", "/usr/bin/gespeaker", "///usr/share/gespeaker/data/icons/gespeaker.svg" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"KW Player", "kwplayer", "/usr/share/icons/hicolor/16x16/apps/kwplayer.png" },
     {"Kid3-qt", "kid3-qt ", "/usr/share/icons/hicolor/16x16/apps/kid3-qt.png" },
     {"Lollypop", "lollypop ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Lollypop.png" },
     {"NetEase Cloud Music", "netease-cloud-music "},
     {"OBS", "obs", "/usr/share/icons/hicolor/256x256/apps/obs.png" },
     {"OSD Lyrics", "osdlyrics", "/usr/share/icons/hicolor/64x64/apps/osdlyrics.png" },
     {"PulseAudio Manager", "paman", "/usr/share/icons/gnome/16x16/devices/audio-card.png" },
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Meter (Capture)", "pavumeter --record", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"PulseAudio Volume Meter (Playback)", "pavumeter", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"XJadeo", "xjadeo", "/usr/share/pixmaps/xjadeo.png" },
     {"bomi", "bomi --wake ", "/usr/share/icons/hicolor/16x16/apps/bomi.png" },
     {"guvcview", "guvcview", "///usr/share/pixmaps/guvcview/guvcview.png" },
     {"lenmus", "lenmus", "/usr/share/pixmaps/lenmus.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"tuxguitar", "tuxguitar ", "/usr/share/icons/hicolor/16x16/apps/tuxguitar.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Cool Retro Term", "cool-retro-term", "/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"FileManager-Actions Configuration Tool", "fma-config-tool"},
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Heimdall", "heimdall-frontend", "/usr/share/pixmaps/heimdall.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"Laptop Mode Tools Configuration", "/usr/sbin/lmt-config-gui-pkexec", "/usr/share/pixmaps/laptop-mode-tools.svg" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"OpenJDK Java 9 Console", "/usr/lib/jvm/java-9-openjdk/bin/jconsole"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"PathFinder", "PathFinder", "/usr/share/pixmaps/PathFinder.png" },
     {"QtEmu", "qtemu", "/usr/share/icons/qtemu.png" },
     {"ROXTerm", "roxterm"},
     {"Terminal", "gnome-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Terminology", "terminology", "/usr/share/icons/terminology.png" },
     {"Termite", "termite", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Tilda", "/usr/bin/tilda", "/usr/share/pixmaps/tilda.png" },
     {"Tilix", "tilix", "/usr/share/icons/hicolor/16x16/apps/com.gexperts.Tilix.png" },
     {"Tint2", "tint2"},
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"WinUSB", "winusbgui", "/usr/share/pixmaps/winusbgui-icon.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"gtk2fontsel", "gtk2fontsel"},
     {"ranger", "xterm -e ranger", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"tkPacman", "/usr/bin/tkpacman", "///usr/share/tkpacman/icons/tkpacman-icon.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

