 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Archive Manager", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"ClipIt", "clipit"},
     {"GVim", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Go For It!", "go-for-it", "/usr/share/icons/hicolor/16x16/apps/go-for-it.svg" },
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.5/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"Qemu Launcher", "qemu-launcher"},
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Shutter", "shutter ", "/usr/share/icons/hicolor/16x16/apps/shutter.png" },
     {"WizNote", "WizNote", "/usr/share/icons/hicolor/16x16/apps/wiznote.png" },
     {"Xchm", "xchm ", "/usr/share/pixmaps/xchm-48.png" },
     {"Zim Desktop Wiki", "zim ", "/usr/share/pixmaps/zim.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"fcitx-qimpanel-configtool", "fcitx-qimpanel-configtool", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"DrRacket", "drracket -singleInstance ", "/usr/share/icons/hicolor/16x16/apps/drracket.png" },
     {"FriCAS", "xterm -e fricas", "/usr/share/pixmaps/fricas.xpm" },
     {"GNU Octave", "/usr/bin/octave --force-gui", "///usr/share/octave/4.0.0/imagelib/octave-logo.svg" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GNU TeXmacs", "texmacs ", "/usr/share/pixmaps/TeXmacs.xpm" },
     {"GeoGebra", "geogebra"},
     {"LenMus", "lenmus", "/usr/share/pixmaps/lenmus.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Mendeley Desktop", "mendeleydesktop ", "/usr/share/icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Redcsl", "xterm -e redcsl", "/usr/share/icons/redcsl.png" },
     {"SageMath", "xterm -e /usr/bin/sage -notebook", "/usr/share/pixmaps/sage-notebook.png" },
     {"Stellarium", "stellarium", "/usr/share/icons/hicolor/16x16/apps/stellarium.png" },
     {"wxMaxima", "/usr/bin/wxmaxima ", "/usr/share/pixmaps/wxmaxima.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"PlayOnLinux", "playonlinux", "///usr/share/playonlinux/etc/playonlinux.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"Xboard", "xboard", "/usr/share/icons/hicolor/48x48/apps/xboard.png" },
     {"mGBA", "mgba-qt ", "/usr/share/icons/hicolor/16x16/apps/mgba.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"DjView4", "djview4 ", "/usr/share/icons/hicolor/32x32/mimetypes/djvulibre-djview4.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"GV", "gv", "/usr/share/pixmaps/gv.xbm" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MComix", "mcomix ", "/usr/share/icons/hicolor/16x16/apps/mcomix.png" },
     {"Scribus", "scribus ", "/usr/share/icons/hicolor/32x32/apps/scribus.png" },
     {"Slideshow", "/usr/bin/slideshow", "///usr/share/racket/slideshow-exe-icon.ico" },
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
     {"feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"115pan", "115pan", "/usr/share/pixmaps/115pan.png" },
     {"Audio assistant", "linphone --run-audio-assistant", "/usr/share/icons/hicolor/48x48/apps/linphone.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BCloud", "bcloud-gui", "/usr/share/icons/hicolor/16x16/apps/bcloud.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"Ekiga Softphone", "ekiga", "/usr/share/icons/hicolor/16x16/apps/ekiga.png" },
     {"Electronic WeChat", "/usr/bin/electronic-wechat", "///usr/share/electronic-wechat/icon.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Linphone", "linphone", "/usr/share/icons/hicolor/48x48/apps/linphone.png" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Point", "/opt/Point/PointDownload/PointDownload", "///opt/Point/PointDownload/point.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Tickr - Feed Reader", "/usr/bin/tickr"},
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Xware Desktop", "/usr/bin/xware-desktop ", "/usr/share/icons/hicolor/16x16/apps/xware-desktop.png" },
     {"Yandex Browser (beta)", "/usr/bin/yandex-browser-beta ", "/usr/share/icons/hicolor/16x16/apps/yandex-browser-beta.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"EclipseTrader", "/usr/share/eclipsetrader/trader", "///usr/share/pixmaps/eclipsetrader.png" },
     {"Edit E-book", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"GV", "gv", "/usr/share/pixmaps/gv.xbm" },
     {"GnuCash", "gnucash ", "/usr/share/icons/hicolor/16x16/apps/gnucash-icon.png" },
     {"Gummi", "gummi ", "/usr/share/pixmaps/gummi.png" },
     {"HTMLDOC", "htmldoc ", "/usr/share/icons/hicolor/16x16/apps/htmldoc.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"LyX Document Processor", "lyx ", "/usr/share/icons/hicolor/48x48/apps/lyx.png" },
     {"ReText", "retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"TeXstudio", "texstudio "},
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
     {"WPS Presentation", "/usr/bin/wpp ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wppmain.png" },
     {"WPS Spreadsheets", "/usr/bin/et ", "/usr/share/icons/hicolor/48x48/apps/wps-office-etmain.png" },
     {"WPS Writer", "/usr/bin/wps ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wpsmain.png" },
     {"Zathura", "zathura "},
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Googleplaydownloader", "googleplaydownloader", "/usr/share/pixmaps/googleplaydownloader.png" },
     {"Logical Volume Management", "/usr/bin/system-config-lvm", "///usr/share/system-config-lvm/pixmaps/lv_icon.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"BlueGriffon", "bluegriffon", "/usr/share/icons/hicolor/16x16/apps/bluegriffon.png" },
     {"Bluefish Editor", "bluefish ", "/usr/share/icons/hicolor/16x16/apps/bluefish.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"DrRacket", "drracket -singleInstance ", "/usr/share/icons/hicolor/16x16/apps/drracket.png" },
     {"DreamPie", "dreampie", "/usr/share/pixmaps/dreampie.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Java Mission Control", "/usr/lib/jvm/java-8-jdk/bin/jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java Monitoring and Management Console", "/usr/lib/jvm/java-8-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java VisualVM", "/usr/lib/jvm/java-8-jdk/bin/jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Julia", "xterm -e julia"},
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.5/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"LiteIDE", "liteide", "/usr/share/pixmaps/liteide.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"OmegaT", "omegat", "/usr/share/pixmaps/omegat.png" },
     {"OpenJDK 1.7.0 Monitoring & Management Console", "_BINDIR_/jconsole"},
     {"OpenJDK 1.7.0 Policy Tool", "_BINDIR_/policytool"},
     {"Poedit", "poedit ", "/usr/share/icons/hicolor/16x16/apps/poedit.png" },
     {"PyCharm", "/usr/bin/pycharm", "/usr/share/pixmaps/pycharm.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"RStudio", "/usr/bin/rstudio-bin ", "/usr/share/icons/hicolor/16x16/apps/rstudio.png" },
     {"Spyder", "spyder ", "/usr/share/pixmaps/spyder.png" },
     {"Spyder3", "spyder3 ", "/usr/share/pixmaps/spyder3.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"Julia", "xterm -e julia"},
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
     {"Spyder", "spyder ", "/usr/share/pixmaps/spyder.png" },
     {"Spyder3", "spyder3 ", "/usr/share/pixmaps/spyder3.png" },
     {"XMaxima", "xterm -e xmaxima", "/usr/share/pixmaps/maxima.png" },
     {"Yacas", "xterm -e yacas", "/usr/share/pixmaps/yacas.png" },
     {"Yacas online documentation", "xdg-open https://yacas.readthedocs.org/", "/usr/share/pixmaps/yacas.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Ardour 4", "ardour4", "///usr/share/ardour4/icons/ardour_icon_256px.png" },
     {"Ario", "ario", "/usr/share/icons/hicolor/16x16/apps/ario.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"FeelUOwn", "FeelUOwn", "///usr/share/feeluown-git/icons/FeelUOwn.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GTK sound mixer", "/usr/bin/aumix", "///usr/share/aumix/aumix.xpm" },
     {"Gespeaker", "/usr/bin/gespeaker", "///usr/share/gespeaker/data/icons/gespeaker.svg" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"KW Player", "kwplayer", "/usr/share/icons/hicolor/16x16/apps/kwplayer.png" },
     {"LenMus", "lenmus", "/usr/share/pixmaps/lenmus.png" },
     {"OSD Lyrics", "osdlyrics", "/usr/share/icons/hicolor/64x64/apps/osdlyrics.png" },
     {"PulseAudio Manager", "paman", "/usr/share/icons/gnome/16x16/devices/audio-card.png" },
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Meter (Capture)", "pavumeter --record", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"PulseAudio Volume Meter (Playback)", "pavumeter", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"XJadeo", "xjadeo", "/usr/share/pixmaps/xjadeo.png" },
     {"guvcview", "guvcview", "///usr/share/pixmaps/guvcview/guvcview.png" },
     {"mpv Media Player", "mpv --profile=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"tuxguitar", "tuxguitar  -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Cool Retro Term", "cool-retro-term", "/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"ROXTerm", "roxterm"},
     {"Termite", "termite", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Tilda", "/usr/bin/tilda", "/usr/share/pixmaps/tilda.png" },
     {"Tint2 panel", "tint2"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

